= Introduction

== Approval Testing

Approval testing is a technique that allows you to compare the output of your code with a known good/previously approved output.

An approval test case will only succeed, if the actually received output is equal to the previously approved output.

If the received output is different from the approved output, the test will fail and leave it to human reviewer to approve received output or to fix the code.

Approval testing is especially useful for testing complex objects or large data sets, where it is impractical to write individual assertions for each property.


== ApproveJ

ApproveJ is a Java implementation of approval testing with a builder-based fluent API, several built-in tools, and optional extension points.

To review the code, file issues or suggest changes, please visit the project's link:https://github.com/mkutz/approvej[GitHub page].


== API Reference

Javadoc for each module is available here:

- link:{javadoc-url}/core/index.html[core] -- core framework
- link:{javadoc-url}/http/index.html[http] -- HTTP stub server
- link:{javadoc-url}/http-wiremock/index.html[http-wiremock] -- WireMock adapter
- link:{javadoc-url}/json-jackson/index.html[json-jackson] -- JSON support (Jackson 2.x)
- link:{javadoc-url}/json-jackson3/index.html[json-jackson3] -- JSON support (Jackson 3.x)
- link:{javadoc-url}/yaml-jackson/index.html[yaml-jackson] -- YAML support (Jackson 2.x)
- link:{javadoc-url}/yaml-jackson3/index.html[yaml-jackson3] -- YAML support (Jackson 3.x)
