= Basics

The general entry point to start an approval is the static initializer `approve` of the link:{javadoc-url}/core/org/approvej/ApprovalBuilder.html[`ApprovalBuilder`].
It takes the object which you want to approve an argument and returns a builder to configure the approval with a fluent API.


[id="approve_strings"]
== Approve Strings

If you have anything that returns an arbitrary string, you can simply build an approval like this

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=approve_strings]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=approve_strings]
----
<1> creates an `ApprovalBuilder<String>`
<2> compares result to a previously approved value stored in a file next to the test and fails the test if the result differs

Executing such a test, will create two files next to the test code file named like `<TestClass>-<testMethod>-received.txt` and `<TestClass>-<testMethod>-approved.txt`.

The received file will always contain a string representation of the object you want to approve at the last execution.

The approved file will be empty at first.
You can use a diff tool of your choice to compare the two files and merge values that you want to approve.
If the received value equals the content of the approved file, the received file will be deleted automatically.

[source,text]
.Approved file
----
include::../../../test/java/examples/java/BasicsDocTest-approve_strings-approved.txt[]
----

You can adjust various details of this process or use no file at all.
See <<verifying>> for more details on how to do that.


[id="approve_pojos"]
== Approve POJOs

Of course, you might want to approve more complex objects than just strings.

For example a simple POJO like this

[source,java,indent=0,role="primary"]
.Person POJO
----
include::../../../testFixtures/java/examples/ExampleClass.java[tag=person_pojo]
----

By default, ApproveJ will simply call the object's `toString` method to turn the object into a string just before verifying.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=approve_pojos]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=approve_pojos]
----
<1> creates an `ApprovalBuilder<Person>` approve the person
<2> compares the `person.toString()` to a previously approved version and fails if they are not equal

[source,text]
.Approved file
----
include::../../../test/java/examples/java/BasicsDocTest-approve_pojos-approved.txt[]
----

See <<printing>> if need a more sophisticated way of printing.


[id="printing"]
== Printing -- customize how values are turned into Strings

While some `toString` implementations already are quite good, they typically return a one-liner.
This is fine as long as you only have a few properties.
However, if you have a lot of properties, it is much easier to read the result if it is formatted nicely.


=== Generic Object Printer

ApproveJ provides a generic link:{javadoc-url}/core/org/approvej/print/ObjectPrinter.html[`ObjectPrinter`] that will print the object with each of its properties on a new line to make comparing the result easier.
You can use this printer by calling the `printWith` method on the builder.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=object_printer]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=object_printer]
----
<1> applies the `ObjectPrinter` and returns a new `ApprovalBuilder<String>`

Now the approved file will look like this

[source,text]
.Approved file
----
include::../../../test/java/examples/java/BasicsDocTest-object_printer-approved.txt[]
----


=== Custom Printer

You can also provide a custom link:{javadoc-url}/core/org/approvej/print/Printer.html[`Printer`]/`Function<T, String>` implementation to the builder's `printWith` method.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=custom_printer]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=custom_printer]
----
<1> applies the given `Printer` and returns a new `ApprovalBuilder<String>`

[source]
.Approved file
----
include::../../../test/java/examples/java/BasicsDocTest-custom_printer-approved.txt[]
----


[id=scrubbing]
== Scrubbing -- make random parts static

Sometimes you might not be able to control the exact output of the object you want to approve.
For example, if the result object contains a timestamp or a generated ID, you might want to ignore these for the approval.

You can do this by using the `scrubbedOf` method of the link:{javadoc-url}/core/org/approvej/ApprovalBuilder.html[`ApprovalBuilder`] and provide a link:{javadoc-url}/core/org/approvej/scrub/Scrubber.html[`Scrubber`]/`UnaryOperator<T>` implementation.

For instance, in the following `BlogPost` POJO there are two generated fields:

[source,java,indent=0,role="primary"]
.Java
----
include::../../../testFixtures/java/examples/ExampleClass.java[tag=blog_post_pojo]
----
<1> the `id` is a UUID that's being generated randomly, and
<2> the `published` is a `LocalDateTime` set to now.

In the flowing example, the two dynamic properties are scrubbed with the built-in Scrubbers for link:{javadoc-url}/core/org/approvej/scrub/Scrubbers.html#uuids()[`uuids`] and link:{javadoc-url}/core/org/approvej/scrub/Scrubbers.html#instants(java.time.format.DateTimeFormatter)[`instants`].

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=scrubbing]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=scrubbing]
----
<1> replaces the published date with a numbered placeholder
<2> replaces the id UUID with a numbered placeholder
<3> so that the verified result looks like this

[source]
.Approved file
----
include::../../../test/java/examples/java/BasicsDocTest-scrubbing-approved.txt[]
----

Generally a built-in `Scrubber` uses a replacement function that replaces all matches with a numbered placeholder in the form of `[<label> <counter>]` (e.g. `[uuid 1]`, `[date 2]`, …).
Note that two matches of the same (e.g. the same UUID in two places) will be replaced with the same placeholder, so you can still see that two scrubbed values were equal.


=== Custom `Scrubber`

The link:{javadoc-url}/core/org/approvej/scrub/RegexScrubber.html[`RegexScrubber`] already allows for a lot of special custom cases.
In case this isn't enough, you can also provide a custom `Scrubber<T>`/`UnaryOperator<T>` implementation to the builder's `scrubbedOf` method.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=custom_scrubbing]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=custom_scrubbing]
----
<1> this custom `Scrubber` specifically the number property of the `Contact` with a constant
<2> so that the verified result looks like this

[source]
.Approved file
----
include::../../../test/java/examples/java/BasicsDocTest-custom_scrubbing-approved.txt[]
----

Note that this `Scrubber` is a `Scrubber<Contact>` and not a `Scrubber<String>`.
Hence, it is necessary to apply it before the `Printer` is applied.

Of course the `Scrubber` can also be defined in a separate class, instead of a lambda.


=== Built-In Scrubbers

All built-in `Scrubber` implementations are available via the  link:{javadoc-url}/core/org/approvej/scrub/Scrubbers.html[Scrubbers] utility class.


[id=verifying]
== Verifying -- adjust the verification

=== `InplaceVerifier`

The link:{javadoc-url}/core/org/approvej/verify/InplaceVerifier.html[`InplaceVerifier`] will verify the result with a directly provided previously approved value.
That way, the approved value is plainly visible in the test code.
However, this might not be practical for large objects.
It also does not allow to use a diff tool to compare the result with the previously approved value.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=verify_inplace]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=verify_inplace]
----


=== `FileVerifier`

The link:{javadoc-url}/core/org/approvej/verify/FileVerifier.html[`FileVerifier`] will verify the result with a previously approved value stored in a file.
It is used in most of the examples above.

If no approved file exists, it will be created as an empty _approved_ file.
The received value will be written to another _received_ file.

If the approved file exists, it will be compared with the received value.
If they are equal, the test will pass.
Any existing received file will be deleted automatically in that case.

If the files are not equal, the test will fail.
The received value will be persisted in a received file.
Any existing received value will be overwritten by this.

You can use a diff tool of your choice to compare the two files and merge values that you want to approve.


==== `NextToTestPathProvider`

By default, the `FileVerifier` will use a link:{javadoc-url}/core/org/approvej/verify/NextToTestPathProvider.html[`NextToTestPathProvider`], which will put the received and approved files next to the test class and name them like the test case method.

You can make this explicit by using the `inFile` method.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=verify_file_next_to_test]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=verify_file_next_to_test]
----
<1> defines the `NextToTestPathProvider` explicitly, same as just calling `verify()`

The `nextToTestAs` method gives you the opportunity to use a different file extension for the approved and received files.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=verify_file_next_to_test_as]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=verify_file_next_to_test_as]
----
<1> this printer will create a YAML version of the object
<2> so it makes sense to change the filename extension, so your IDE will apply appropriate syntax highlighting


==== `DirectoryNextToTestPathProvider`

If you have test classes with a lot of approval tests, there a quite a lot of files created next to the test class.
In that case, you might want to use a link:{javadoc-url}/core/org/approvej/verify/DirectoryNextToTestPathProvider.html[`DirectoryNextToTestPathProvider`], which will create a directory next to the test class and put the approved and received files in there.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=verify_file_directory_next_to_test_as]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=verify_file_directory_next_to_test_as]
----


==== `BasePathProvider`

It is possible to use a link:{javadoc-url}/core/org/approvej/verify/PathProvider.html[`PathProvider`] to configure where the files are stored.
The default `NextToTestPathProvider` will analyze the stack trace of the test method and create a path based on the class name and method of the executed test.

Alternatively, you can use a `BasePathProvider` to specify the path of the approved file.
The received file will be put next to the approved file and the filename will contain the word `received`.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=verify_file_base_path]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=verify_file_base_path]
----
<1> this will expect the approved file at this path, the received file will be created next to it at `src/test/resources/BasicsDocTest-verify_file_base_path-reveived.yaml`


==== Customer `PathProvider`

You can also define your own link:{javadoc-url}/core/org/approvej/verify/FileVerifier.PathProvider.html[`PathProvider`].
