= Basics

The general entry point to start an approval is the static initializer `approve` of the link:{javadoc-url}/core/org/approvej/ApprovalBuilder.html[`ApprovalBuilder`].
It takes the object which you want to approve as an argument and returns a builder to configure the approval with a fluent API.


[id="approve_strings"]
== Approve Strings

If you have anything that returns an arbitrary string, you can simply build an approval like this

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=approve_strings]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=approve_strings]
----
<1> creates an `ApprovalBuilder<String>`
<2> compares result to a previously approved value stored in a file next to the test and fails the test if the result differs

Executing such a test, will create two files next to the test code file named like `<TestClass>-<testMethod>-received.txt` and `<TestClass>-<testMethod>-approved.txt`.

The received file will always contain a string representation of the object you want to approve at the last execution.

The approved file will be empty at first.
You can use a diff tool of your choice to compare the two files and merge values that you want to approve.
If the received value equals the content of the approved file, the received file will be deleted automatically.

[source,text]
.Approved file
----
include::../../../test/java/examples/java/BasicsDocTest-approve_strings-approved.txt[]
----

You can adjust various details of this process:

- <<printing>>
- <<scrubbing>>
- <<approving>>
- <<reviewing>>


[id="approve_pojos"]
== Approve POJOs

Of course, you might want to approve more complex objects than just strings.

For example a simple POJO like this

[source,java,indent=0]
.Person POJO
----
include::../../../testFixtures/java/examples/ExampleClass.java[tag=person_pojo]
----

By default, ApproveJ will simply call the object's `toString` method to turn the object into a string just before approving it.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=approve_pojos]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=approve_pojos]
----
<1> creates an `ApprovalBuilder<Person>` approve the person

Will approve the following value:

[source,text]
.Approved file
----
include::../../../test/java/examples/java/BasicsDocTest-approve_pojos-approved.txt[]
----

See <<printing>> if need a more sophisticated way of printing.


[id=named]
== Named Approvals -- approve multiple values per test case

Optionally, you can assign a specific name for an approval.
When you <<approve_by_file>> the chosen name will be added to the filename to help identify the specific approval.
It is also necessary to assign a name if there are multiple approvals per test case, as otherwise later approvals will overwrite earlier ones.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=approve_named]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=approve_named]
----

This test generates two sets of files

1. <TestClass>-<testMethod>-*jane*-<received/approved>.txt
2. <TestClass>-<testMethod>-*john*-<received/approved>.txt
