= Basics

The general entry point to start an approval is the static initializer `approve` of the link:{javadoc-url}/core/org/approvej/ApprovalBuilder.html[`ApprovalBuilder`].
It takes the object which you want to approve as an argument and returns a builder to configure the approval with a fluent API.


[id="approve_strings"]
== Approve Strings

If you have anything that returns an arbitrary string, you can simply build an approval like this

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=approve_strings]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=approve_strings]
----
<1> creates an `ApprovalBuilder<String>`
<2> compares result to a previously approved value stored in a file next to the test and fails the test if the result differs

Executing such a test, will create two files next to the test code file named like `<TestClass>-<testMethod>-received.txt` and `<TestClass>-<testMethod>-approved.txt`.

The received file will always contain a string representation of the object you want to approve at the last execution.

The approved file will be empty at first.
You can use a diff tool of your choice to compare the two files and merge values that you want to approve.
If the received value equals the content of the approved file, the received file will be deleted automatically.

[source,text]
.Approved file
----
include::../../../test/java/examples/java/BasicsDocTest-approve_strings-approved.txt[]
----

You can adjust various details of this process:

- <<printing>>
- <<scrubbing>>
- <<approving>>


[id="approve_pojos"]
== Approve POJOs

Of course, you might want to approve more complex objects than just strings.

For example a simple POJO like this

[source,java,indent=0]
.Person POJO
----
include::../../../testFixtures/java/examples/ExampleClass.java[tag=person_pojo]
----

By default, ApproveJ will simply call the object's `toString` method to turn the object into a string just before approving it.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=approve_pojos]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=approve_pojos]
----
<1> creates an `ApprovalBuilder<Person>` approve the person

Will approve the following value:

[source,text]
.Approved file
----
include::../../../test/java/examples/java/BasicsDocTest-approve_pojos-approved.txt[]
----

See <<printing>> if need a more sophisticated way of printing.


[id="printing"]
== Printing -- customize how values are turned into Strings

While some `toString` implementations already are quite good, they typically return a one-liner.
This is fine as long as you only have a few properties.
However, if you have a lot of properties, it is much easier to read the result if it is formatted nicely.

In order to change the way objects are being transformed to strings, you can use the link:{javadoc-url}/core/org/approvej/ApprovalBuilder.html[`ApprovalBuilder`]'s `printWith` method and provide a link:{javadoc-url}/core/org/approvej/print/Printer.html[`Printer`]/`Function<T, String>` instance as an argument.


=== Generic Object Printer

ApproveJ provides a generic link:{javadoc-url}/core/org/approvej/print/ObjectPrinter.html[`ObjectPrinter`] that will print the object with each of its properties on a new line to make comparing the result easier.
You can use this printer by calling the `printWith` method on the builder.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=object_printer]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=object_printer]
----
<1> applies the `ObjectPrinter` and returns a new `ApprovalBuilder<String>`

Now the approved file will look like this

[source,text]
.Approved file
----
include::../../../test/java/examples/java/BasicsDocTest-object_printer-approved.txt[]
----


[id=custom_printer_function]
=== Custom Printer Function

You can provide a custom `Function<T, String>` to the builder's `printWith` method.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=custom_printer_function]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=custom_printer_function]
----
<1> applies the given `Function` and returns a new `ApprovalBuilder<String>`

So the content of the approved file will look like this

[source]
.Approved file
----
include::../../../test/java/examples/java/BasicsDocTest-custom_printer_function-approved.txt[]
----


[id=custom_printer_implementation]
=== Custom Printer Implementation

For more complex cases, you can implement your own link:{javadoc-url}/core/org/approvej/print/Printer.html[`Printer`].

This will allow you to also override the `filenameExtension` method.
If you use a link:{javadoc-url}/core/org/approvej/approve/FileApprover.html[`FileApprover`] (see <<approving>>), it will be used to determine the files' filename extension.
This is useful, if your `Printer` creates a certain format (e.g. JSON, XML, YAML, …).

E.g. the following implementation will print a `Person` as a YAML string.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=person_yaml_printer]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=person_yaml_printer]
----

The resulting file will look like this

[source,yaml]
.Approved file
----
include::../../../test/java/examples/java/BasicsDocTest-custom_printer-approved.yaml[]
----


[id=scrubbing]
== Scrubbing -- make random parts static

Sometimes you might not be able to control the exact output of the object you want to approve.
For example, if the result object contains a timestamp or a generated ID, you might want to ignore these for the approval.

You can do this by using the `scrubbedOf` method of the link:{javadoc-url}/core/org/approvej/ApprovalBuilder.html[`ApprovalBuilder`] and provide a link:{javadoc-url}/core/org/approvej/scrub/Scrubber.html[`Scrubber`]/`UnaryOperator<T>` implementation.

For instance, in the following `BlogPost` POJO there are two generated fields:

[source,java,indent=0,role="primary"]
.Java
----
include::../../../testFixtures/java/examples/ExampleClass.java[tag=blog_post_pojo]
----
<1> the `id` is a UUID that's being generated randomly, and
<2> the `published` is a `LocalDateTime` set to now.

In the flowing example, the two dynamic properties are scrubbed with the built-in Scrubbers for link:{javadoc-url}/core/org/approvej/scrub/Scrubbers.html#uuids()[`uuids`] and link:{javadoc-url}/core/org/approvej/scrub/Scrubbers.html#instants(java.time.format.DateTimeFormatter)[`instants`].

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=scrubbing]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=scrubbing]
----
<1> replaces the published date with a numbered placeholder
<2> replaces the id UUID with a numbered placeholder
<3> so that the approved result looks like this

[source]
.Approved file
----
include::../../../test/java/examples/java/BasicsDocTest-scrubbing-approved.txt[]
----

Generally a built-in `Scrubber` uses a replacement function that replaces all matches with a numbered placeholder in the form of `[<label> <counter>]` (e.g. `[uuid 1]`, `[date 2]`, …).
Note that two matches of the same (e.g. the same UUID in two places) will be replaced with the same placeholder, so you can still see that two scrubbed values were equal.


=== Custom `Scrubber`

The link:{javadoc-url}/core/org/approvej/scrub/RegexScrubber.html[`RegexScrubber`] already allows for a lot of special custom cases.
In case this isn't enough, you can also provide a custom link:{javadoc-url}/core/org/approvej/scrub/Scrubber.html[`Scrubber<T>`]/`UnaryOperator<T>` implementation to the builder's `scrubbedOf` method.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=custom_scrubbing]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=custom_scrubbing]
----
<1> this custom `Scrubber` specifically replaces the number property of the `Contact` with a constant

[source]
.Approved file
----
include::../../../test/java/examples/java/BasicsDocTest-custom_scrubbing-approved.txt[]
----

Note that this `Scrubber` is a `Scrubber<Contact>` and not a `Scrubber<String>`.
Hence, it is necessary to apply it _before_ the `Printer` is applied.

In case you want to reuse the `Scrubber`, you can also define in a separate class implementing the link:{javadoc-url}/core/org/approvej/scrub/Scrubber.html[`Scrubber<T>`] interface.


=== Built-In `Scrubbers`

All built-in `Scrubber` implementations are available via the link:{javadoc-url}/core/org/approvej/scrub/Scrubbers.html[Scrubbers] utility class.


[id=approving]
== Approving -- adjust the verification

You conclude the link:{javadoc-url}/core/org/approvej/ApprovalBuilder.html[`ApprovalBuilder`] by specifying `by` which link:{javadoc-url}/core/org/approvej/approve/Approver.html[`Approver`] the received value should be approved.


=== Approve by Value

The link:{javadoc-url}/core/org/approvej/ApprovalBuilder.html#byValue(java.lang.String)[`ApprovalBuilder.byValue()`] method will use an link:{javadoc-url}/core/org/approvej/approve/InplaceApprover.html[`InplaceApprover`] to approve the received value by comparison with a directly provided previously approved value.
That way, the approved value is plainly visible in the test code.
However, this might not be practical for large objects.
It also does not allow to use a diff tool to compare the result with the previously approved value.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=approve_inplace]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=approve_inplace]
----


=== Approve by File

The link:{javadoc-url}/core/org/approvej/ApprovalBuilder.html#byFile()[`ApprovalBuilder.byFile()`] method will use a link:{javadoc-url}/core/org/approvej/approve/FileApprover.html[`FileApprover`] to approve the received value by comparison a previously approved value stored in a file.
It is used in most of the examples above.

If no approved file exists, it will be created as an empty _approved_ file.
The received value will be written to another _received_ file.

If the approved file exists, it will be compared with the received value.
If they are equal, the test will pass.
Any existing received file will be deleted automatically in that case.

If the files are not equal, the test will fail.
The received value will be persisted in a received file.
Any existing received value will be overwritten by this.

You can use a diff tool of your choice to compare the two files and merge values that you want to approve.


==== Next to Test

By default, the `FileApprover` will use a link:{javadoc-url}/core/org/approvej/approve/NextToTestPathProvider.html[`NextToTestPathProvider`], which will put the received and approved files next to the test class and name them like the test case method.

You can make this explicit by using the `nextToFile` method.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=approve_file_next_to_test]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=approve_file_next_to_test]
----
<1> defines the `NextToTestPathProvider` explicitly, same as just calling `byFile()`


.File structure
----
.
└── 📁src/test/java/…
    ├── 📄 <TestClass>.java
    ├── 📄 <TestClass>-<testMethod>-approved.txt
    └── 📄 <TestClass>-<testMethod>-received.txt
----

==== Custom Filename Extension

The link:{javadoc-url}/core/org/approvej/approve/NextToTestPathProvider.html#filenameExtension(java.lang.String)[`NextToTestPathProvider.filenameExtension`] method gives you the opportunity to use a different file extension for the approved and received files.

NOTE:: most of the time you probably want to do this because you're using a special printer that creates a specific format (e.g. JSON, XML, YAML, …).
In that case, you might want to provide a <<custom_printer_implementation>> and override the `filenameExtension` method of the `Printer` instead of changing the filename extension here.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=approve_file_custom_extension]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=approve_file_custom_extension]
----
<1> this printer will create a YAML version of the object
<2> so it makes sense to change the filename extension, so your IDE will apply appropriate syntax highlighting

.File structure with custom filename extension
----
.
└── 📁src/test/java/…
    ├── 📄 <TestClass>.java
    ├── 📄 <TestClass>-<testMethod>-approved.<filenameExtension>
    └── 📄 <TestClass>-<testMethod>-received.<filenameExtension>
----


==== In a Subdirectory

If you have test classes with a lot of approval tests, there a quite a lot of files created next to the test class.
In that case, you can use the link:{javadoc-url}/core/org/approvej/approve/NextToTestPathProvider.html#inSubdirectory()[`NextToTestPathProvider.inSubdirectory`] method to instruct the link:{javadoc-url}/core/org/approvej/approve/NextToTestPathProvider.html[`NextToTestPathProvider`] to put all the files in a subdirectory named after the test class.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=approve_file_nextToTestInSubdirectory]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=approve_file_nextToTestInSubdirectory]
----

.File structure with subdirectory
----
.
└── 📁src/test/java/…
    ├── 📁 <TestClass>
    │   ├── 📄 <testMethod>-approved.txt
    │   └── 📄 <testMethod>-received.txt
    └── 📄 <TestClass>.java
----


==== Given Path

Alternatively, you can simply specify the path of the approved file.
If the given approved file path contains the word `approved` just before the filename extension, it will be replaced with `received` in the to determine the received file path.
Otherwise, the word `received` will be added at the end of the filename.

For example

- `src/test/resources/BasicsDocTest-approve_file_approved_path-approved.yaml` ->
  `src/test/resources/BasicsDocTest-approve_file_approved_path-received.yaml`
- `src/test/resources/BasicsDocTest-approve_file_approved_path.yaml` ->
  `src/test/resources/BasicsDocTest-approve_file_approved_path-received.yaml`.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/BasicsDocTest.java[tag=approve_file_approved_path]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/BasicsDocTest.kt[tag=approve_file_approved_path]
----
<1> this will expect the approved file at this path, the received file will be created next to it at `src/test/resources/BasicsDocTest-approve_file_approved_path-reveived.yaml`

.File structure with given path
----
.
└── 📁src/test/java/…
│   └── 📄 <TestClass>.java
└── 📁src/test/resources
    ├── 📄 src/test/resources/BasicExamples-approve_file_approved_path.yaml
    └── 📄 src/test/resources/BasicExamples-approve_file_approved_path-received.yaml
----


==== Custom `PathProvider`

You can also define your own link:{javadoc-url}/core/org/approvej/approve/FileApprover.PathProvider.html[`PathProvider`] and pass it to the `byFile` method.

In that case, you might want to take advantage of the link:{javadoc-url}/core/org/approvej/approve/StackTraceTestFinderUtil.html[`StackTraceTestFinderUtil`] class to find the test source path or the current test method based on the current stack trace.


=== Built-In `PathProviders`

All built-in link:{javadoc-url}/core/org/approvej/approve/PathProvider.html[`PathProvider`] implementations are available via the link:{javadoc-url}/core/org/approvej/approve/PathProviders.html[`PathProviders`] utility class.


== Configuration

Optionally you can configure the default behaviors of ApproveJ by putting an `approvej.properties` file into your resource folder of your test suite (e.g. `src/test/resources/approvej.properties`).

.Example `approvej.properties`
----
include::../../../test/resources/approvej.properties[]
----

Supported properties are:

`defaultPrinter`:: the default printer class if none is specified via the `printWith` method (see <<printing>>)
