= JSON with Jackson

The `json-jackson` module provides several JSON-related features impelemented with https://github.com/FasterXML/jackson[Jackson].

To use it, you need to add it as a dependency to your project.

.Gradle
[source,groovy,subs=attributes+,role="primary"]
----
implementation 'org.approvej:json-jackson:{revnumber}'
----
.Gradle.kts
[source,kotlin,subs=attributes+,role="secondary"]
----
implementation("org.approvej:json-jackson:{revnumber}")
----
.Maven
[source,xml,subs=attributes+,role="secondary"]
----
<project>
  <!-- … -->
  <dependencies>
    <dependency>
      <groupId>org.approvej</groupId>
      <artifactId>json-jackson</artifactId>
      <version>{revnumber}</version>
    </dependency>
  </dependencies>
  <!-- … -->
</project>
----


== Scrub JSON

The link:{javadoc-url}/json-jackson/org/approvej/json/jackson/JsonPointerScrubber.html[`JsonPointerScrubber`] can be used to scrub a JSON node identified by a https://javadoc.io/doc/com.fasterxml.jackson.core/jackson-core/latest/com/fasterxml/jackson/core/JsonPointer.html[`JsonPointer`].

Compared to generic `Scrubber<String>` implementations this is particularly useful when there are several values matching the same pattern, but only one of them needs to be scrubbed.
For instance, if you have a JSON containing two UUIDs, one that was generated by the code (and hence needs to be scrubbed) and one that is a reference to another resource and should not be scrubbed.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/JsonJacksonDocTest.java[tag=scrub_json_pointer]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/JsonJacksonDocTest.kt[tag=scrub_json_pointer]
----
<1> scrubs the dynamically assigned `id` node on the root level of the JSON and replaces it with "[scrubbed id]"
<2> scrubs the `published` timestamp node on the root level of the JSON and replaces it with "[scrubbed published]"
<3> stores the received data at a file next to the test with the file extension `.json`

[source,json]
.Approved file
----
include::../../../test/java/examples/java/JsonJacksonDocTest-scrub_json_pointer-approved.json[]
----


== Pretty Print JSON

In the example above, the JSON persisted in a one-liner.
Even for the simple example, this is not very readable, let alone easily comparable to a slightly different JSON.
To improve this, you can use the link:{javadoc-url}/json-jackson/org/approvej/json-jackson/JsonPrettyPrinter.html.html[`JsonPrettyPrinter`].

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/JsonJacksonDocTest.java[tag=pretty_print_json]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/JsonJacksonDocTest.kt[tag=pretty_print_json]
----
<1> applies the `JsonPrettyPrinter` to convert the `JsonNode` object to a string

Now the approved file is much more readable.

[source,json]
.Approved file
----
include::../../../test/java/examples/java/JsonJacksonDocTest-pretty_print_json-approved.json[]
----


== Pretty Print JSON Strings

Sometimes you might not need/want to parse a received JSON string into a `JsonNode` object.
In this case, you can use the `JsonStringPrettyPrinter` to pretty print a JSON string directly.

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/JsonJacksonDocTest.java[tag=pretty_print_json_string]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/JsonJacksonDocTest.kt[tag=pretty_print_json_string]
----
<1> applies the `JsonPrettyPrinter` to convert the `JsonNode` object to a string

[source,json]
.Approved file
----
include::../../../test/java/examples/java/JsonJacksonDocTest-pretty_print_json_string-approved.json[]
----

Note that the applied scrubbers also replaced the tag IDs.
