[id=configuration]
= Configuration -- global defaults and environment settings

ApproveJ can be configured through multiple mechanisms to customize its default behavior.
This allows you to set global defaults, override them per project, and further override them via environment variables.


[id="configuration_sources"]
== Configuration Sources

Configuration values are resolved in the following order (highest to lowest priority):

1. *Environment variables* - e.g., `APPROVEJ_DEFAULT_PRINT_FORMAT`
2. *Project properties file* - `src/test/resources/approvej.properties`
3. *User home properties file* - `~/.config/approvej/approvej.properties`
4. *Default values*

This hierarchy allows you to:

- Set global defaults in your home directory
- Override them per project in the project's properties file
- Further override them via environment variables (useful for CI/CD pipelines)

See the <<cheat_sheet_configuration,cheat sheet>> for a complete list of all supported properties.


[id="custom_extensions"]
== Custom Extensions

ApproveJ uses a Service Provider Interface (SPI) mechanism that allows you to register custom print formats and reviewers.
These can then be referenced by alias in the configuration.


[id=custom_extensions_print_format_provider]
=== Custom Print Format Provider

To create a custom print format that can be configured via alias:

1. Implement `PrintFormat<T>` and `PrintFormatProvider<T>`
2. Register it via `META-INF/services/org.approvej.configuration.Provider`

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/ScreamingPrintFormat.java[]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/ScreamingPrintFormat.kt[]
----

.`src/test/resources/META-INF/services/org.approvej.configuration.Provider`
[source]
----
examples.java.ScreamingPrintFormat
----

Now you can use it in configuration:

[source,properties]
----
defaultPrintFormat = screaming
----


[id=custom_extensions_reviewer_provider]
=== Custom File Reviewer Provider

To create a custom file reviewer that can be configured via alias:

1. Implement `FileReviewer` and `FileReviewerProvider`
2. Register it via `META-INF/services/org.approvej.configuration.Provider`

[source,java,indent=0,role="primary"]
.Java
----
include::../../../test/java/examples/java/LoggingFileReviewer.java[]
----
[source,kotlin,indent=0,role="secondary"]
.Kotlin
----
include::../../../test/kotlin/examples/kotlin/LoggingFileReviewer.kt[]
----

.`META-INF/services/org.approvej.configuration.Provider`
[source]
----
examples.java.LoggingFileReviewer
----

Now you can use it in configuration:

[source,properties]
----
defaultFileReviewer = logging
----
