#!/bin/bash

if [[ -z "$1" ]]; then
  echo "Version input is required."
  exit 1
fi

VERSION="$1"

rm -rf pages/*
mkdir -p pages/img
cp favicon.png pages/img/
./gradlew asciidoc -Pversion=$VERSION
mv manual/build/docs/asciidoc/* pages/

mkdir pages/javadoc
./gradlew javadoc -Pversion=$VERSION
for javadoc_dir in modules/*/build/docs/javadoc; do
  module_path=${javadoc_dir#modules/}
  module_name=${module_path%%/*}
  mv "$javadoc_dir" "pages/javadoc/$module_name"
done
