GET /something
Connection: Upgrade, HTTP2-Settings
Host: {{Host}}
Http2-settings: AAEAAEAAAAIAAAAAAAMAAAAAAAQBAAAAAAUAAEAAAAYABgAA
Upgrade: h2c
User-agent: {{User-agent}}
X-my-header: some header value
