name: Build PR

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '**.adoc'

jobs:
  build:
    permissions:
      checks: write
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest

    env:
      JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
      JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
      JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}

    steps:

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - uses: gradle/actions/setup-gradle@cd4b95f1dffd155d6d8f6b8c195a3ff2f9f77a5d

      - run: ./gradlew check

      - run: ./gradlew jreleaserConfig -Pversion=0.0.1-SNAPSHOT --git-root-search

      - name: cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - run: ./gradlew build jacocoTestReport sonar
        if: ${{ github.event.pull_request.user.login != 'dependabot[bot]' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: modules-test-reports
          path: modules/**/build/reports/tests/test/

      - name: Enable auto merge for Dependabot PRs
        run: |
          gh pr review --approve "${{ github.event.pull_request.html_url }}"
          gh pr merge --auto --rebase --delete-branch "${{ github.event.pull_request.html_url }}"
        if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
