name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - run: ./gradlew assemble

      - run: ./gradlew jreleaserDeploy --info -Pversion=${{ github.event.inputs.version }} -PdryRun=false
        env:
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jreleaser-problem-report
          path: build/reports/problems/problems-report.html
          if-no-files-found: ignore
