name: Submit Dependencies

on:
  push:
    branches:
      - main
    paths:
      - 'gradle/libs.versions.toml'
  workflow_dispatch:

jobs:
  build:
    permissions:
      checks: write
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin

      - uses: gradle/actions/dependency-submission@748248ddd2a24f49513d8f472f81c3a07d4d50e1
